version: '3.4'
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
    volumes:
      - "./tmp:/tmp/localstack"

  localstack-setup:
    build:
      context: .
      dockerfile: Dockerfile.localstack-setup
    image: localstack-setup
    depends_on:
      - localstack