version: '3.4'
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=my-access-key
      - AWS_SECRET_ACCESS_KEY=key
      - AWS_SECRET_KEY=secret
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
      - DEBUG=1
      - USE_SSL=0
    volumes:
      - "./localstack/entrypoint:/docker-entrypoint-initaws.d"
      - "./localstack/dynamo-tables:/setup"
      - "./localstack/tmp:/tmp/localstack"
